# Generated by Django 5.2.3 on 2025-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message with the recording request'),
        ),
        migrations.AddField(
            model_name='recordingrequest',
            name='recipient_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('meeting_manager', 'Meeting Manager')], default='moderator', max_length=20),
        ),
    ]
