# Generated by Django 5.2.3 on 2025-07-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_recordingrequest_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='room',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='When the meeting starts', null=True),
        ),
    ]
